server:
  port: 8008
  context-path: /smbasic
# 自定义druid属性
druid-custom:
  view:
    # druid StatViewServlet host黑白名单，用户名密码
    # deny优先级高于allow
    allow: 127.0.0.1
    deny: 192.168.2.102
    username: root
    password: root
#logging:
#  file: log.log
mybatis:
  # MyBatis配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  # mapper扫描路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 实体类别名
  type-aliases-package: com.spring.boot.entity
spring:
  datasource:
    # 数据库相关配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbasic?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 30
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的sql
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true